### ISSUE TITLE
Error when terrain mapper is not active

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-elevation-ruler#115]
https://ptb.discord.com/channels/915186263609454632/1193755370607345695/1257140842846752849

Uncaught Error: undefined. Flag scope "terrainmapper" is not valid or not currently active
[Detected 3 packages: elevationruler, lib-wrapper, aedifs-tactical-grid]
    at Scene.getFlag (foundry-esm.js:11771:44)
    at Ruler._addWaypoint (Ruler.js:157:70)

**Comment by Someone2345** [comment]
Yup - it acts the same as the 107 issues. 

(I was going to add this as a new bug, but I see that it has already been noted)

Hi, I am afraid that the issues caused by switching to the measure distance tools (as per 107) are still in effect after updating. 

It looks like the main cause may now be "flag scop terrian mapper". 
Same actions to replicate as before - switch from dragging token using the token select tool to the measure distance tool and all token actions effectively break. 
There is a new error message in the console. 

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/75526961/9a727b03-1ff6-4908-a903-f39cf4dcb3d7)


Not tested with no other modules yet.
FVTT v12.328
D&D5e 3.2.1
[Releases 0.9.6)

[Confirmed that if terrainmapper module is added, then the error is resolved.]

**Comment by caewok** [comment]
Fixed in v0.9.7
