### ISSUE TITLE
bug with how you handle levels modules

### ISSUE THREAD

**Issue by Simolsen** [caewok/fvtt-elevation-ruler#12]
![image](https://user-images.githubusercontent.com/79066296/209242164-f57b85ab-3cdb-4c16-9e6f-406b12cd2460.png)
it seem like a nice ider tho atm it seem to happen no matter what you do with levels and elevation-ruler installed side by side even while the ui is not open i like the module but something have to be done

i'm willing to help testing if needed

**Comment by caewok** [comment]
Yes, seems like maybe some updates to Levels messed with this. I will investigate; thanks!

**Comment by caewok** [comment]
In v0.6.3, I added a setting so you can decide whether to display Levels labels only when the Level UI is active or all the time or not at all. 

I believe this is otherwise working correctly. The ruler appears to be defaulting to the elevation at the bottom of the tile for a given level. But if that is not the case, please feel free to add some additional details and I can try to replicate.
