### ISSUE TITLE
Bug: Erroneous calculations

### ISSUE THREAD

**Issue by VladGrant** [caewok/fvtt-elevation-ruler#17]
In certain cases, specifically when doing some diagonal changes the distance calculation is simply wrong. In this case the distance is 10ft which is not possible. The same happens when I only use the ruler as well. This occurs when only elevation ruler and libwrapper are enabled as well. 

System is dnd5e, v10 or Foundry.
 
![image](https://user-images.githubusercontent.com/12880220/226210115-27c8ef24-3ca7-4697-a9e8-9fed54fa82d8.png)

**Comment by 9ryex5** [comment]
Yes, this shouldn't happen
![image](https://user-images.githubusercontent.com/43207603/229302851-8703286e-a6d4-42b8-b3d9-7f3c0961ede3.png)

**Comment by 9ryex5** [comment]
The previously example was trying to move a token (with [Drag Ruler](https://foundryvtt.com/packages/drag-ruler)). This one is just the ruler.
Both examples should show the same value because they are measuring the same distance. But even showing different values none of them is correct (token should show 8.66, and ruler 9 (rounded))
![image](https://user-images.githubusercontent.com/43207603/229312269-c7f93b22-9844-48d1-afad-26fd4f1922bb.png)

**Comment by caewok** [comment]
Fixed in 0.6.6. There may be a bit of a rounding issue with dnd5e using Euclidean distance: see https://github.com/foundryvtt/dnd5e/issues/2257. I also spotted a potential issue with 5/10/5 measurements on hex grids in dnd5e: https://github.com/foundryvtt/dnd5e/issues/2256.
