### ISSUE TITLE
Double rounding errors in 0.10.3 on a square grid

### ISSUE THREAD

**Issue by pandanielxd** [caewok/fvtt-elevation-ruler#181]
On version 0.10.3 there seems to be an issue with rounding measuring certain distances, adding decimal places where they should not be. I tested this on Foundry V12 331 on the Worlds without Number system (1.4.7) with the equidistant square grid diagonals. (Except for libWrapper no other modules enabled)

An example below:

![example](https://i.imgur.com/UKq2rM3.gif)

**Comment by caewok** [comment]
This is likely due to the path points not always being set to dead-center of the grid square. Try 0.10.6. There are also a few settings that can affect how these measurements are done:

- Round Distance to Multiple. Probably set this to 1 to enforce rounding.
- Use Grid for Movement Penalties. Enable to force penalties to be measured based on grid squares.
- Pathfinding Snap to Grid. Enable to strongly encourage pathfinding to stick to grid centers. As the hint says, it should snap to centers unless doing so will cause the movement to get blocked (e.g., moving through an off-center, small doorway).

**Comment by pandanielxd** [comment]
Works great now, thanks for all the hard work!
