### ISSUE TITLE
Not working on PF2e

### ISSUE THREAD

**Issue by NdranC** [caewok/fvtt-elevation-ruler#191]
System v12.331
PF2e v6.3.1

![image](https://github.com/user-attachments/assets/e9b18189-ce73-48ac-8b6d-8c236240a30c)

Just reinstalled the module to test it out again and I am getting this error. No ruler shows up when I try to move tokens and some tokens I can't move at all.

I'm unsure if it's related but a week ago I had to disable this module because in the middle of the session two players complained that they couldn't drag their tokens anymore (wasd still worked) while another player was able to move theirs fine. I wasn't having a problem as a gm moving the tokens of the players affected.

**Comment by caewok** [comment]
This error might be because you are trying to use Terrain Mapper but something is preventing Terrain Mapper from loading. Scroll up in the browser console to see if there are other errors. I cannot replicate this, so it is probably a module conflict. If you narrow down the modules that you are using when this occurs and give me a list, I can trouble shoot.

**Comment by NdranC** [comment]
![image](https://github.com/user-attachments/assets/09a4d0f2-5346-4496-8654-ed12fc47230a)
This might be what you are referencing.

I disabled terrainmapper and it now works. I guess that means the problem is in the terrainmapper side of things. I still get the error above even when I disable elevation ruler. I'll make a bug report on terrainmapper's github. Thank you.
