### ISSUE TITLE
Weirdness when going through tokens

### ISSUE THREAD

**Issue by NdranC** [caewok/fvtt-elevation-ruler#196]
[Screencast from 2024-09-04 15-52-34.webm](https://github.com/user-attachments/assets/601433bb-a8a9-44be-b69f-a8577f42d08e)

The construct on the right is an enemy monster.
The goblin on the left is a player character.

When trying to move past the construct on the right, the travel distance (10ft) is wrong, it should be (15ft).
When trying to move past the goblin player on the left, the travel distance is right (10ft).
Both show (12ft) as a total travel distance. Unsure as to why.
Both show a (-0ft) terrain icon that I'm also unsure what it's about. It only shows when you try to move through a token.

![image](https://github.com/user-attachments/assets/836bbe29-accb-4b8e-9c4f-c3e8d2bd68a6)
These are my settings. No other mods enabled except the minimum required. No red errors in console.

EDIT:
I forgot to add what happens when I try to use pathfinding
![image](https://github.com/user-attachments/assets/d1911ea1-e06f-48f6-a32b-f1dc64cac67d)

**Comment by caewok** [comment]
Couple things going on here. The 5-10-5 fix in v0.10.9 should help. The -0 is because your 5' rounding setting was rounding the value back to 0; I fixed that so if it gets rounded to 0, it won't display the cost. Also, your cost setting is set to a flat +2, which is probably not what you want. So it was doing 5 + 2, but then rounding the 2 back down to 0.

**Comment by NdranC** [comment]
Thank you. I finally found the time to test it. I didn't realize the setting for the flat penalties applied to the percentage field as well. My bad. On a quick glance everything looks correct. Except for one more thing I'm gonna create a new issue for.
