### ISSUE TITLE
When using Euclidian distance, diagonal movement is sometimes shown as terrain penalty

### ISSUE THREAD

**Issue by nschoenwald** [caewok/fvtt-elevation-ruler#218]
I'm afraid I can't describe this issue very well as it's hard to understand what is happening, but the ruler is showing up like this even without any difficult terrain on the map:

<img width="261" alt="Bildschirmfoto 2024-10-10 um 17 25 25" src="https://github.com/user-attachments/assets/de77902d-2748-49f5-a8df-cea4c41247d7">
<img width="542" alt="image" src="https://github.com/user-attachments/assets/56657ec2-96ea-4285-87fd-25de049cb16c">
<img width="544" alt="image" src="https://github.com/user-attachments/assets/f4b4ebaf-4898-4e06-9b26-88fc221124e8">
<img width="543" alt="image" src="https://github.com/user-attachments/assets/465962f7-a4dc-472b-801b-f0349bf3a42d">

**Comment by caewok** [comment]
It is because you have "Use Grid for Movement Penalties" checked. That is rounding movement based on the grid, which is not really consistent with measuring using Euclidean distance. The rounding is causing the ruler to identify the discrepancy between the rounded measurement and the euclidean distance as a movement penalty.

**Comment by caewok** [comment]
Addressed in v0.10.16.
