### ISSUE TITLE
Performance / Frame rate drop while moving tokens with WASD arrow keys 

### ISSUE THREAD

**Issue by sperckest** [caewok/fvtt-elevation-ruler#230]
video
https://github.com/user-attachments/assets/50d33f47-cd1c-4544-a220-1a89556f8c02

recommend playing video in half speed. 

Noticed performance hit to Foundry VTT while using elevation ruler add-on.

Did some testing and found a few scenarios that demonstrate the buggy feature.

This test is using frames per second as the benchmark. (Lag) is use as an equivalent to Frame Rate Drop.

Lag was produced while using WASD or arrow keys to move tokens. based on the contents of the token more or less lag was observed. as seen in the table below.
Dragging tokens produce very little lag

![Table](https://github.com/user-attachments/assets/fd1f15a2-670a-41f0-bf0e-f5742f14ef48)

Elevation ruler 10.10 was the latest update that show NO lag.

Elevation ruler 10.11 - 10.15 all show the same lag.

Tried various Elevation ruler setting with no change to out come.

Used D&D 5e (4.1.2) and (4.0.4) for testing both are stable and are affected when Elevation ruler is enabled.

lag seems to increase while train mapper is enabled.

The scene in the video was simple and the lag was noted.

The lag is seen on the player's or GM's web browser that is moving the token and is not seen on the player's or GM's web browser viewing the action.

Thank you for being awesome. This add-on is really appreciated.

**Comment by Belodri** [comment]
I've been facing this issue as well, though in D&D 3.3.1. It happens whenever a new movement measurement is started (be that though a single press of WASD or by starting the drag ruler).

I'm pretty sure the source of this issue is the cloning of the actor in the `TokenClone` constructor in `/scripts/measurement/MovePenalty.js`.
Here's an example using using a character with 201 items in total:

The log of starting to move a token by using the drag ruler, using these logpoints:
![image](https://github.com/user-attachments/assets/9b6c5da3-2fdf-4341-9081-2cd16f3d138e)

```
17:11:57.988
elevationruler|_getMeasurementSegments [Ruler.js:339:42](http://localhost:30000/modules/elevationruler/scripts/Ruler.js)
17:11:57.989 TokenClone constructor start [MovePenalty.js:28:4](http://localhost:30000/modules/elevationruler/scripts/measurement/MovePenalty.js)
17:11:59.282 TokenClone constructor end [MovePenalty.js:30:2](http://localhost:30000/modules/elevationruler/scripts/measurement/MovePenalty.js)
17:11:59.432
elevationruler|_getMeasurementSegments [Ruler.js:339:42](http://localhost:30000/modules/elevationruler/scripts/Ruler.js)
17:11:59.434
movementCostForSegment [MovePenalty.js:275:15](http://localhost:30000/modules/elevationruler/scripts/measurement/MovePenalty.js)
```

Hope this info helps somewhat and thanks for all your work!

**Comment by sperckest** [comment]
THANK YOU!

**Comment by strlys** [comment]
I faced the same problem in my world. Players were facing massive lag while moving, so I had to deactivate for a temporary fix. I'm also in DnD 3.3.1, and even using only the ruler, my players face this problem.

**Comment by sperckest** [comment]
Thank you Belodri,

Cloning an actor variable with  ```.clone()``` makes sense if one wants to prevent mutations of the original variable.
However if there is no changing of the variable ,Read only,  then just a reference to the variable should work.

I feel it is computationally expensive if one duplicates the entire token every call to move. This is present when using WASD arrow keys, making it called several times a second.


I may of found a fix that I have yet to see any side effects,

Version 10.15 of elevation ruler

In Foundry VTT Addons folder:
“elevationruler/scripts/measurement/MovePenalty.js”
I changed some code:

From
``` javascript
  constructor(token) {
    this.actor = token.actor.clone();
    this._original = token;
  }
```

To
``` javascript
  constructor(token) {
    this.actor = token.actor;
    this._original = token;
  }

```

Although I did not check to see if this conflicts with the rest of the code. I do see significant improvement to performance and lag removal. 


Thank you all for being awesome!

I plan on closing the issue when a fix is applied to elevation ruler release.
Until then removing  ```.clone()``` is a nice temporary fix.

**Comment by caewok** [comment]
@sperckest Sorry, but the actor needs to be cloned. Otherwise, the movement speed will not get calculated correctly for anything with terrains. That is because active effects need to be applied / unapplied to the token to see if they change movement speed. The code already does quite a bit of caching to avoid performance issues related to this.

But outside of Terrain Mapper, I don't think clone is necessary. So I will try to add some rules to only use it when terrain regions are present.

**Comment by caewok** [comment]
A bit more explanation of what might be causing the performance issue:
`MovePenalty.prototype.moveSpeedWithinRegions` calculates the speed of the token when it is (going to be) moved into 1+ regions. Any given region can apply active effects to the token actor, which may modify token speed. To determine this without affecting the underlying actor, the actor is cloned prior to applying the terrain effects. The speed is then calculated and cached:

```js
    // Duplicate the token clone and add the region terrain(s).
    const tClone = this.#localTokenClone.duplicate();
    Terrain.addToTokenLocally(tClone, [...terrains.values()], { refresh: false });
    // Does not work for DAE: tClone.actor.applyActiveEffects();
    tClone.actor.prepareData(); // Slower but works with DAE.

    // Determine the speed of the token clone and cache for future reference.
    const speed = SPEED.tokenSpeed(tClone, this.movementType);
    this._regionPenaltyMap.set(key, speed);
```

Ideally, I would not need to clone an actor or prepare its data in order to determine what would happen if I applied active effects to the actor. But I have yet to find a better way to do this, as it does not appear to be well-supported in Foundry.

**Comment by caewok** [comment]
In v0.10.16, I fell back to using `tClone.actor.applyActiveEffects` unless using dnd5e v3. In v3, `applyActiveEffects` did not work with DAE. But as `prepareData` does not work at all, I would much rather have something that works in v4 (and bonus, is faster). I might add a few extra tests to avoid this cloning when no region terrain effects are present.

**Comment by sperckest** [comment]
Thank you for being awesome.
