### ISSUE TITLE
[Feature Suggestion] Allow friendly units to count as difficult terrain, and enemies to be impassable

### ISSUE THREAD

**Issue by GhostwheelX** [caewok/fvtt-elevation-ruler#37]
Would it be possible to do as the title suggests for those of us playing within the D&D 5e ruleset?

**Comment by caewok** [comment]
This module has a setting for you to treat tokens as difficult terrain. Just set the relevant movement penalty.

By enemies being impassable, I assume you mean that pathfinding will take you around them, not through them. That is technically possible, but difficult for at least two reasons:

1. It requires the scene graph of all the walls to be re-calculated before any pathfinding, if any enemy token has moved. This calcuation usually is only done when walls change position. Not impossible, but a performance hit. It could be faster if I could incrementally adjust the scene graph, but the triangulation library I am currently using cannot do that. And I am a bit limited because I need a constrained Delauney triangulation library, not just a Delauney triangulation library.
2. It requires special handling of the token shapes. The scene graph ensures that no walls have a collinear overlap. Token edges have collinear overlaps with walls all the time. So some work will be necessary here.

I will probably do this at some point, just saying it is not as easy as you might imagine.

**Comment by caewok** [comment]
Okay, so I think I have pulled this off in v0.8.3! I refactored the underlying scene graph to handle overlapping walls/token edges, which was probably necessary anyway if I expect this to work with terrains or scene regions. We will see if I got all the bugs out!

For each user, it recalculates the scene graph when a wall or token changes position. If the user setting for avoiding tokens is not enabled, it skips recalculation for tokens. So for users with slower computers, turning off token avoidance would be preferable. Then, if you start a pathfinding, it re-triangulates the scene based on the graph as necessary. I didn't see any lag, but my computer is fast. YMMV. 

Note also that if the setting is to avoid hostile tokens, it considers friendly tokens to be hostile to an enemy token. So that token avoidance works as you would expect if you are the GM.
