### ISSUE TITLE
Integration with ETL

### ISSUE THREAD

**Issue by OmegaRogue** [caewok/fvtt-elevation-ruler#44]
There is a replacement module for the old enhanced terrain layer module https://github.com/reyzor1991/pf2e-wiki/wiki/ETL that works pretty much like the old one. It would be nice to have support for that and drag ruler in elevation ruler, as terrain mapper doesn't really work well together with pf2e.

**Comment by caewok** [comment]
I won't support Drag Ruler. It doesn't make sense to have two rulers that both display a ruler when dragging tokens. They will certainly conflict.

I won't support ETL, because that appears to be just a module.json link. If someone properly takes over the ETL git and updates it to v11, then I may reconsider. But with scene regions coming in v12, there may be little point.

That said, the wiki you linked to did give me an idea. In v0.8.5, I added a range selector in the Drawing configuration (go to the text tab) so you can set a movement bonus/penalty. Elevation Ruler will pick up on that. Pretty simple way to make a difficult terrain area. You can also set an elevation for the drawing in the config (go to the position tab). If set, it will limit the move bonus/penalty only for tokens at that specific elevation. Hopefully that acts as a decent stopgap, until v12 comes along.
