### ISSUE TITLE
Enhancement: Add swim speed

### ISSUE THREAD

**Issue by ravingdragoon** [caewok/fvtt-elevation-ruler#50]
Would it be possible to add a swim speed option to the manual speed selection?

**Comment by caewok** [comment]
In v0.8.9, you can add additional options to the speed selection either using a macro or a world script. 

Example:
```js
// Example: Add a swim movement to the api.
CONFIG.elevationruler.MOVEMENT_TYPES.SWIM = 3; // Increment by 1 from the highest-valued movement type
CONFIG.elevationruler.MOVEMENT_BUTTONS[CONFIG.elevationruler.MOVEMENT_TYPES.SWIM] = "person-swimming"; // From Font Awesome
CONFIG.elevationruler.SPEED.ATTRIBUTES.SWIM = "actor.system.attributes.movement.swim"; // dnd5e
```

**Comment by tnarv** [comment]
I know this is marked as closed but due to the way PF2e's speeds are handled the above does not work since there is no way to set the swim attribute properly. And the code in the module doesn't appear that it would check it for it anyway in PF2e's case.

It would be very nice if the module natively handled swim and climb speeds in systems that have it.
