### ISSUE TITLE
#62 Does not appear to be fixed in 0.8.11

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-elevation-ruler#65]
#62 Does not appear to be fixed in 0.8.11
It has gotten worse, in fact. Instead of working the first time, it doesn't work any of the times. It always shows green no matter how far you walk. The prior section is calculated correctly but it never shows yellow for beyond normal movement or red beyond 2 times movement.

**Comment by caewok** [comment]
I fixed a bug that hopefully addresses this. Turns out that if the Token HUD had not been used, a flag was not set and so it was defaulting to not knowing movement. So when I tested it originally, my tokens worked fine, but adding a new token revealed the bug. So try v0.8.12 and let me know if this issue still persists. Thanks!
