### ISSUE TITLE
[Feature Request] Hold Alt to skip animations

### ISSUE THREAD

**Issue by NdranC** [caewok/fvtt-elevation-ruler#69]
I would be nice if you could replicate a feature from the original drag ruler. Holding Alt would allow you to skip animations when moving a token. Great for DMs trying to set things up in place.

**Comment by caewok** [comment]
In v12, I added the ability to hold the "F" button when triggering a token move to skip animations. That is based on the new ability of Foundry animations in v12 to "teleport" and skip the movement animation. So sorry, probably won't make it to v11.

(I am loathe to set this to Alt because of how overloaded Alt tends to be.)
