### ISSUE TITLE
[Bug] Hostile Creature Blocking Incorrect Calculation

### ISSUE THREAD

**Issue by 117ksk** [caewok/fvtt-elevation-ruler#88]
When the feature to enforce hostile create blocking pathing is enabled, medium creatures cannot move diagonally around a large hostile creature with proper movement calculation as per rules. 

How the calculation works now (10ft movement for one diagonal square):
![Screenshot 2024-06-14 162657](https://github.com/caewok/fvtt-elevation-ruler/assets/113755707/a57ba4ba-3dcb-4aee-a006-3731a2f61fce)

How the calculation should be (5ft movement for first single diagonal square):
![Screenshot 2024-06-14 162750](https://github.com/caewok/fvtt-elevation-ruler/assets/113755707/0eb7b008-21bd-4d20-be34-6ca28afb25e7)

The hostile creature blocking feature is really awesome, however it appears to be calculated in such a way as to include this bug in these movement situations.

**Comment by caewok** [comment]
In v0.9.6, I added a config option, `CONFIG.elevationruler.tokenPathfindingBuffer`. It adds or subtracts to the token border, in pixel increments for purposes of pathfinding. By default, I set it to -1, meaning the token border is shrunk inward by 1 pixel. This fixes the issue you saw.

I will say that it is not a perfect fix, because pathfinding still is going to prefer to keep some distance between any obstacle (including blocking tokens) and the path. Feel free to play with that value, noting that until you either reset the scene or move the blocking token, the pathfinding will not reflect the update.
